<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AWSProjectType>Lambda</AWSProjectType>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="3.3.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="3.0.1" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.14.1" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="3.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../VerificationEngine.Services/VerificationEngine.Services.csproj" />
  </ItemGroup>
</Project>
