using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using VerificationEngine.Services.Vendors;

namespace VerificationEngine.Services.Documents;

/// <summary>
/// Shared letterhead, footer and signature block for every generated document, so the
/// three form types look like they belong to the same product rather than three
/// independently-styled PDFs.
/// </summary>
public abstract class PdfDocumentBase
{
    // Mirrors the design system's accent-verified / ink tokens - the PDF should read as
    // the same product as the web app, not a generic invoice template.
    protected static readonly string AccentVerified = "#0F6E5C";
    protected static readonly string InkPrimary = "#1B2430";
    protected static readonly string InkSecondary = "#5C6670";

    protected byte[] Render(string documentTitle, string claimId, Action<ColumnDescriptor> body, SignatureRecord signature)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(10).FontColor(InkPrimary));

                page.Header().Column(header =>
                {
                    header.Item().Row(row =>
                    {
                        row.RelativeItem().Text("Verification Engine").FontSize(16).SemiBold().FontColor(AccentVerified);
                        row.ConstantItem(150).AlignRight().Text($"Claim {claimId}").FontSize(8).FontColor(InkSecondary);
                    });
                    header.Item().PaddingTop(4).LineHorizontal(1).LineColor(AccentVerified);
                    header.Item().PaddingTop(12).Text(documentTitle).FontSize(20).SemiBold();
                });

                page.Content().PaddingTop(16).Column(column =>
                {
                    body(column);

                    column.Item().PaddingTop(24).Element(c => SignatureBlock(c, signature));
                });

                page.Footer().Column(footer =>
                {
                    footer.Item().LineHorizontal(0.5f).LineColor(InkSecondary);
                    footer.Item().PaddingTop(4).Row(row =>
                    {
                        row.RelativeItem().Text(
                            "Generated by Verification Engine. Vendor-sourced fields marked " +
                            $"{MockNotice.Prefix} are simulated for demonstration - see the project README.")
                            .FontSize(7).FontColor(InkSecondary);
                        row.ConstantItem(80).AlignRight().Text(x =>
                        {
                            x.Span("Page ").FontSize(7).FontColor(InkSecondary);
                            x.CurrentPageNumber().FontSize(7).FontColor(InkSecondary);
                            x.Span(" / ").FontSize(7).FontColor(InkSecondary);
                            x.TotalPages().FontSize(7).FontColor(InkSecondary);
                        });
                    });
                });
            });
        });

        return document.GeneratePdf();
    }

    protected static void Field(ColumnDescriptor column, string label, string? value)
    {
        column.Item().PaddingBottom(8).Row(row =>
        {
            row.ConstantItem(160).Text(label).FontColor(InkSecondary).FontSize(9);
            row.RelativeItem().BorderBottom(1).BorderColor("#DDE3E0").PaddingBottom(2)
                .Text(string.IsNullOrWhiteSpace(value) ? "-" : value).SemiBold();
        });
    }

    protected static void SectionHeading(ColumnDescriptor column, string text) =>
        column.Item().PaddingTop(8).PaddingBottom(8).Text(text).FontSize(13).SemiBold().FontColor(AccentVerified);

    private static void SignatureBlock(IContainer container, SignatureRecord signature)
    {
        container.Border(1).BorderColor("#DDE3E0").Padding(12).Column(column =>
        {
            column.Item().Text("Electronic Signature").FontSize(9).SemiBold().FontColor(AccentVerified);
            column.Item().PaddingTop(4).Text($"Signed by: {signature.SignerName}").FontSize(9);
            column.Item().Text($"Signed at (UTC): {signature.SignedAt.UtcDateTime:yyyy-MM-dd HH:mm:ss}").FontSize(9);
            column.Item().PaddingTop(2).Text($"Signature hash (SHA-256): {signature.Sha256Hash}")
                .FontFamily(Fonts.Consolas, "Courier New").FontSize(7).FontColor(InkSecondary);
            column.Item().PaddingTop(4).Text(
                "This is a hashed, timestamped record of a signature captured in-app, not an accredited " +
                "Advanced Electronic Signature under ECTA - see the project README.")
                .FontSize(7).Italic().FontColor(InkSecondary);
        });
    }
}
